# This file was auto-generated by Fern from our API Definition.

from typing import Any, Dict, Optional


def remove_none_from_dict(original: Dict[str, Optional[Any]]) -> Dict[str, Any]:
    new: Dict[str, Any] = {
        key: value for key, value in original.items() if value is not None
    }
    return new
